name: >
  Build Mythic Engine
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 * * *"
    
jobs:
  build:
    name: Build Engine
    runs-on: macos-latest
    
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
          with:
            path: repo

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.12.1

        - name: Create Engine folder
          run: mkdir -p Engine

        - name: Update taps
          run: |
            brew tap homebrew/cask-versions

        - name: Install python dependencies # todo: cache
          run: |
            python -m pip install --upgrade pip
            pip install requests

        - name: Execute python script to get DXVK
          run: python repo/get_dxvk.py # versions.plist, store dxvk version

        - name: Untar DXVK and move it to the Engine folder
          run: |
            mkdir Engine/dxvk
            tar -xzvf dxvk.tgz --strip-components=1 -C Engine/dxvk
  
        - name: Install latest staging build of wine
          run: brew install -v --cask wine-staging
  
        - name: Move wine into Engine folder
          run: mv /Applications/Wine\ Staging.app/Contents/Resources/wine Engine

        - name: Copy D3DMetal lib to Engine
          run: ditto -V repo/lib Engine/wine

        - name: Compress engine as .tar.xz
          run: tar -cJvf Engine.txz Engine
  
        - name: Upload Archive
          uses: actions/upload-artifact@v2
          with:
            name: Engine
            path: Engine.txz
