name: >
  Build Mythic Engine
on:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    
jobs:
  build:
    name: Build Engine
    runs-on: macos-latest
    
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Create Engine folder
          run: mkdir -pv Engine

        - name: Update taps
          run: brew tap homebrew/cask-versions

        - name: Install DXVK
          run: |
            new_asset_name="dxvk.tgz" # NAME OF THE DOWNLOADED FILE
            
            json=$(curl -s "https://api.github.com/repos/doitsujin/dxvk/releases/latest")
            
            dxvk_version=$(echo "$json" | jq -r '.tag_name[1:]')
            asset_name="dxvk-${dxvk_version}.tar.gz"
            asset_url=$(echo "$json" | jq -r --arg asset_name "$asset_name" '.assets[] | select(.name == $asset_name) | .browser_download_url')
            
            if [ "$asset_url" == "null" ]; then
                echo "Unable to locate $asset_name"
                exit 1
            fi
            
            echo "Downloading DXVK $dxvk_version: $asset_name"
            if ! curl -L -o "$new_asset_name" "$asset_url"; then
                echo "Failed to download DXVK $dxvk_version"
                exit 1
            fi
            
            echo "Successfully downloaded DXVK $dxvk_version as archive $new_asset_name"

        - name: Untar DXVK and move it to the Engine folder
          run: |
            mkdir Engine/dxvk
            tar -xzvf dxvk.tgz --strip-components=1 -C Engine/dxvk

        - name: Download the latest winetricks script (master="latest version") and mark it as executable
          run: |
            curl -o winetricks https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
            chmod +x winetricks

        - name: Move winetricks into Engine folder
          run: mv winetricks Engine
  
        - name: Install latest staging build of wine
          run: brew install -v --cask --no-quarantine wine-staging
  
        - name: Move wine into Engine folder
          run: mv /Applications/Wine\ Staging.app/Contents/Resources/wine Engine

        - name: Copy D3DMetal lib to Engine
          run: ditto -V lib/ Engine/wine/lib/

        - name: Compress engine as .tar.xz
          run: tar -cJvf Engine.txz Engine
  
        - name: Upload Archive
          uses: actions/upload-artifact@v4
          with:
            name: Engine
            path: Engine.txz
